---
# -- API Token for Cloudflared default lan tunnel token
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-default-lan-token
  namespace: network
stringData:
  token: eyJhIjoiYjY2YWU3Mzc4ZmZlNDIyNWQ3MDJhMmNkZDMwYWQ1ZmQiLCJ0IjoiZjhmZDc1ZWQtYTQ4Yi00NGFiLTkzNjYtMjU5MmFlZDUxMzQzIiwicyI6Ik56a3dPVE13WkRBdFkyTm1OQzAwTldNMkxXSmxObVl0TjJZeFptWmpNRGMyTURJNSJ9
